-- require("everforest").setup({
--   background = "hard",
--   italics=true,
--   ui_contrast = "high",
--   diagnostic_text_highlight = true,
-- })
--
--
-- vim.cmd('set background=dark')
-- vim.cmd("colorscheme everforest")
