vim.cmd('set background=dark')
vim.cmd('let g:gruvbox_material_background="soft"')
vim.cmd('let g:gruvbox_material_enable_italic=1')
vim.cmd('let g:gruvbox_material_enable_bold=1')
vim.cmd('let g:gruvbox_material_diagnostic_virtual_text="colored"')
vim.cmd('let g:gruvbox_material_diagnostic_text_highlight="1"')
vim.cmd('let g:gruvbox_material_diagnostic_line_highlight="1"')
vim.cmd('let g:gruvbox_material_current_word="underline"')
vim.cmd('let g:gruvbox_material_transparent_background="2"')
vim.cmd('let g:gruvbox_material_visual="red background"')
vim.cmd('let g:gruvbox_material_menu_selection_background="red"')

vim.cmd('colorscheme gruvbox-material')
