-- require('mini.completion').setup()
require('mini.cursorword').setup()
require('mini.extra').setup()
require('mini.files').setup()
require('mini.indentscope').setup()
require('mini.notify').setup()
require('mini.pick').setup()
require('mini.statusline').setup()
require("mini.starter").setup()
require('mini.tabline').setup()
require('mini.visits').setup()
require('mini.diff').setup({ view = { style = 'sign' }})
